/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    playlists: Playlist;
    media: Media;
    gallery: Gallery;
    testimonials: Testimonial;
    faq: Faq;
    staff: Staff;
    'admissions-inquiries': AdmissionsInquiry;
    'tour-bookings': TourBooking;
    'summer-camp-registrations': SummerCampRegistration;
    'admission-applications': AdmissionApplication;
    redirects: Redirect;
    users: User;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    playlists: PlaylistsSelect<false> | PlaylistsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    'admissions-inquiries': AdmissionsInquiriesSelect<false> | AdmissionsInquiriesSelect<true>;
    'tour-bookings': TourBookingsSelect<false> | TourBookingsSelect<true>;
    'summer-camp-registrations': SummerCampRegistrationsSelect<false> | SummerCampRegistrationsSelect<true>;
    'admission-applications': AdmissionApplicationsSelect<false> | AdmissionApplicationsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'seo-settings': SeoSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'seo-settings': SeoSettingsSelect<false> | SeoSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Build the page from sections. Order = top-to-bottom on the page.
   */
  layout: (
    | HeroBlock
    | RichTextBlock
    | CardsGridBlock
    | StatsBlock
    | MediaBlockType
    | GalleryBlockType
    | TestimonialsBlockType
    | FAQBlockType
    | CTABandBlock
    | FormBlockType
  )[];
  publishedAt?: string | null;
  /**
   * URL path segment. Auto-generated from the title if left blank.
   */
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  parent?: (number | null) | Page;
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  background?: ('purple' | 'white' | 'navy') | null;
  /**
   * Types the heading out, then fades in the subhead + buttons. Use sparingly (e.g. homepage).
   */
  animateHeading?: boolean | null;
  eyebrow?: string | null;
  heading: string;
  amharicSubline?: string | null;
  subhead?: string | null;
  image?: (number | null) | Media;
  /**
   * Optional. A path/URL (e.g. /images/...) used as the hero background when no image is uploaded.
   */
  bgImage?: string | null;
  links?:
    | {
        link: {
          appearance?: ('primary' | 'outline' | 'secondary') | null;
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          label: string;
          reference?: (number | null) | Page;
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  background?: ('white' | 'offwhite' | 'purple' | 'navy') | null;
  width?: ('narrow' | 'wide') | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsGridBlock".
 */
export interface CardsGridBlock {
  background?: ('white' | 'offwhite' | 'mist' | 'purple') | null;
  eyebrow?: string | null;
  heading?: string | null;
  intro?: string | null;
  /**
   * Optional HTML id for in-page links (e.g. "activities" → #activities).
   */
  anchor?: string | null;
  columns?: ('2' | '3' | '4') | null;
  cards?:
    | {
        icon?: (number | null) | Media;
        /**
         * Lucide icon name (e.g. GraduationCap, ShieldCheck, Sprout). Used when no icon image is uploaded. See lucide.dev/icons.
         */
        iconName?: string | null;
        title: string;
        description?: string | null;
        enableLink?: boolean | null;
        link?: {
          appearance?: 'link' | null;
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          label: string;
          reference?: (number | null) | Page;
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardsGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  background?: ('purple' | 'navy' | 'white') | null;
  items?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlockType".
 */
export interface MediaBlockType {
  kind?: ('image' | 'video') | null;
  image?: (number | null) | Media;
  videoUrl?: string | null;
  caption?: string | null;
  width?: ('contained' | 'wide' | 'full') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlockType".
 */
export interface GalleryBlockType {
  heading?: string | null;
  source?: ('category' | 'manual') | null;
  category?: ('campus' | 'classroom' | 'stem' | 'agriculture' | 'sports' | 'events' | 'arts') | null;
  limit?: number | null;
  items?: (number | Gallery)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'galleryBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  category: 'campus' | 'classroom' | 'stem' | 'agriculture' | 'sports' | 'events' | 'arts';
  mediaType?: ('image' | 'video') | null;
  image?: (number | null) | Media;
  videoUrl?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlockType".
 */
export interface TestimonialsBlockType {
  heading?: string | null;
  background?: ('white' | 'offwhite' | 'purple') | null;
  source?: ('featured' | 'manual') | null;
  items?: (number | Testimonial)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  authorName: string;
  /**
   * e.g. "Parent of Grade 3 student" or "Alumnus, Class of 2024".
   */
  relationship?: string | null;
  photo?: (number | null) | Media;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlockType".
 */
export interface FAQBlockType {
  heading?: string | null;
  source?: ('category' | 'manual') | null;
  category?: ('general' | 'admissions' | 'fees' | 'curriculum' | 'campus') | null;
  items?: (number | Faq)[] | null;
  renderSchema?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'general' | 'admissions' | 'fees' | 'curriculum' | 'campus';
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABandBlock".
 */
export interface CTABandBlock {
  background?: ('purple' | 'navy' | 'offwhite') | null;
  heading: string;
  subhead?: string | null;
  links?:
    | {
        link: {
          appearance?: ('primary' | 'outline') | null;
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          label: string;
          reference?: (number | null) | Page;
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlockType".
 */
export interface FormBlockType {
  formType: 'inquiry' | 'tour' | 'registration' | 'fee-request' | 'summer-camp';
  background?: ('offwhite' | 'white' | 'purple') | null;
  heading?: string | null;
  intro?: string | null;
  successMessage?: string | null;
  /**
   * Optional HTML id for in-page links (e.g. "register" → #register).
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  category?: ('news' | 'academics' | 'admissions' | 'campus-life' | 'parent-resources' | 'newsletter') | null;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Optional local/stock image path (e.g. /images/...) used if no hero image is uploaded.
   */
  heroImageUrl?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Newsletter magazine sections. When present (category "Newsletter"), the article renders as a visual magazine layout from these sections; the content field above is the plain fallback.
   */
  sections?:
    | {
        heading?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        style?: ('auto' | 'gallery' | 'highlight') | null;
        images?:
          | {
              image?: (number | null) | Media;
              /**
               * Optional local image path used if no image is uploaded.
               */
              imageUrl?: string | null;
              alt?: string | null;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional local video path (e.g. /video/newsletter/...). Plays inline on the website; excluded from the PDF version.
         */
        videoUrl?: string | null;
        /**
         * Optional poster image path shown before the video plays.
         */
        videoPoster?: string | null;
        videoCaption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Newsletter series this article belongs to (e.g. Summer Camp 2026).
   */
  playlist?: (number | null) | Playlist;
  /**
   * Order inside the series (1 = first part).
   */
  playlistPart?: number | null;
  authors?: (number | User)[] | null;
  publishedAt?: string | null;
  /**
   * URL path segment. Auto-generated from the title if left blank.
   */
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playlists".
 */
export interface Playlist {
  id: number;
  title: string;
  /**
   * One or two sentences shown on the series page and series cards.
   */
  description?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Optional local image path (e.g. /images/newsletter/...) used if no cover is uploaded.
   */
  coverImageUrl?: string | null;
  /**
   * URL path segment. Auto-generated from the title if left blank.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Super Admin = full control. Staff = manage content only.
   */
  role: 'super-admin' | 'staff';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  name: string;
  /**
   * e.g. "Head of Primary".
   */
  role: string;
  department?:
    | ('leadership' | 'early-years' | 'primary' | 'stem' | 'languages' | 'arts' | 'pe' | 'operations' | 'front-office')
    | null;
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Show on the Leadership page.
   */
  isLeadership?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admissions-inquiries".
 */
export interface AdmissionsInquiry {
  id: number;
  parentName: string;
  email: string;
  phone?: string | null;
  childAge?: string | null;
  childGrade?: string | null;
  childAgeOrGrade?: string | null;
  interest?: ('general' | 'registration' | 'fee-request' | 'admissions' | 'summer-camp') | null;
  message?: string | null;
  /**
   * Page the form was submitted from.
   */
  sourcePage?: string | null;
  status?: ('new' | 'contacted' | 'enrolled' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-bookings".
 */
export interface TourBooking {
  id: number;
  parentName: string;
  email: string;
  phone?: string | null;
  childAge?: string | null;
  childGrade?: string | null;
  childAgeOrGrade?: string | null;
  preferredDate?: string | null;
  preferredTime?: ('morning' | 'afternoon') | null;
  /**
   * Marketing attribution, chosen by the parent on the contact form.
   */
  heardAbout?: string | null;
  notes?: string | null;
  sourcePage?: string | null;
  status?: ('new' | 'confirmed' | 'completed' | 'cancelled') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "summer-camp-registrations".
 */
export interface SummerCampRegistration {
  id: number;
  parentName: string;
  email: string;
  phone?: string | null;
  childAge?: string | null;
  childGrade?: string | null;
  preferredCampus?: string | null;
  message?: string | null;
  /**
   * Page the form was submitted from.
   */
  sourcePage?: string | null;
  status?: ('new' | 'confirmed' | 'completed' | 'cancelled') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admission-applications".
 */
export interface AdmissionApplication {
  id: number;
  /**
   * Auto-composed from the child’s first / middle / last name on submit.
   */
  studentName: string;
  previousSchool?: string | null;
  previousCurriculum?: string | null;
  currentGrade?: string | null;
  gradeApplyingTo?: string | null;
  preferredCampus?: string | null;
  /**
   * Date the parent submitted the form (YYYY-MM-DD).
   */
  applicationDate?: string | null;
  childFirstName: string;
  childMiddleName?: string | null;
  childLastName: string;
  gender?: ('male' | 'female') | null;
  /**
   * YYYY-MM-DD
   */
  dateOfBirth?: string | null;
  placeOfBirth?: string | null;
  nationality?: string | null;
  citizenship?: string | null;
  passportNumber?: string | null;
  motherTongue?: string | null;
  secondLanguage?: string | null;
  /**
   * Which parent/guardian the school should contact first.
   */
  primaryContact?: string | null;
  fatherSalutation?: string | null;
  fatherFirstName?: string | null;
  fatherMiddleName?: string | null;
  fatherLastName?: string | null;
  fatherNationality?: string | null;
  fatherOccupation?: string | null;
  fatherPassport?: string | null;
  fatherPassportExpiry?: string | null;
  fatherNationalId?: string | null;
  fatherMobile?: string | null;
  fatherBusinessPhone?: string | null;
  fatherEmergencyPhone?: string | null;
  fatherEmail?: string | null;
  fatherWorkEmail?: string | null;
  motherSalutation?: string | null;
  motherFirstName?: string | null;
  motherMiddleName?: string | null;
  motherLastName?: string | null;
  motherNationality?: string | null;
  motherOccupation?: string | null;
  motherPassport?: string | null;
  motherPassportExpiry?: string | null;
  motherNationalId?: string | null;
  motherMobile?: string | null;
  motherBusinessPhone?: string | null;
  motherEmergencyPhone?: string | null;
  motherEmail?: string | null;
  motherWorkEmail?: string | null;
  hasSiblings?: boolean | null;
  isStaffChild?: boolean | null;
  siblingDetails?: string | null;
  hasHealthConditions?: boolean | null;
  needsTreatment?: boolean | null;
  healthDetails?: string | null;
  hasLearningNeeds?: boolean | null;
  hasDisability?: boolean | null;
  learningNeedsDetails?: string | null;
  hasAllergies?: boolean | null;
  allergyDetails?: string | null;
  cat4Verbal?: string | null;
  cat4Quantitative?: string | null;
  cat4NonVerbal?: string | null;
  cat4Spatial?: string | null;
  mediaConsent?: boolean | null;
  parentsSeparated?: boolean | null;
  transportInterest?: boolean | null;
  heardAbout?: string | null;
  /**
   * Typed full name: the parent’s electronic signature on the declaration.
   */
  declarationName?: string | null;
  declarationAccepted?: boolean | null;
  /**
   * Page the form was submitted from.
   */
  sourcePage?: string | null;
  status?: ('new' | 'reviewing' | 'assessment' | 'accepted' | 'enrolled' | 'declined') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Source path, e.g. /old-page (leading slash, no domain).
   */
  from: string;
  /**
   * Destination path or absolute URL.
   */
  to: string;
  type?: ('301' | '302') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'createCollectionImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'playlists';
        value: number | Playlist;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'admissions-inquiries';
        value: number | AdmissionsInquiry;
      } | null)
    | ({
        relationTo: 'tour-bookings';
        value: number | TourBooking;
      } | null)
    | ({
        relationTo: 'summer-camp-registrations';
        value: number | SummerCampRegistration;
      } | null)
    | ({
        relationTo: 'admission-applications';
        value: number | AdmissionApplication;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        cardsGrid?: T | CardsGridBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        mediaBlock?: T | MediaBlockTypeSelect<T>;
        galleryBlock?: T | GalleryBlockTypeSelect<T>;
        testimonialsBlock?: T | TestimonialsBlockTypeSelect<T>;
        faqBlock?: T | FAQBlockTypeSelect<T>;
        ctaBand?: T | CTABandBlockSelect<T>;
        formBlock?: T | FormBlockTypeSelect<T>;
      };
  publishedAt?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  background?: T;
  animateHeading?: T;
  eyebrow?: T;
  heading?: T;
  amharicSubline?: T;
  subhead?: T;
  image?: T;
  bgImage?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              appearance?: T;
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  background?: T;
  width?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsGridBlock_select".
 */
export interface CardsGridBlockSelect<T extends boolean = true> {
  background?: T;
  eyebrow?: T;
  heading?: T;
  intro?: T;
  anchor?: T;
  columns?: T;
  cards?:
    | T
    | {
        icon?: T;
        iconName?: T;
        title?: T;
        description?: T;
        enableLink?: T;
        link?:
          | T
          | {
              appearance?: T;
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  background?: T;
  items?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlockType_select".
 */
export interface MediaBlockTypeSelect<T extends boolean = true> {
  kind?: T;
  image?: T;
  videoUrl?: T;
  caption?: T;
  width?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlockType_select".
 */
export interface GalleryBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  source?: T;
  category?: T;
  limit?: T;
  items?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlockType_select".
 */
export interface TestimonialsBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  background?: T;
  source?: T;
  items?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlockType_select".
 */
export interface FAQBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  source?: T;
  category?: T;
  items?: T;
  renderSchema?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABandBlock_select".
 */
export interface CTABandBlockSelect<T extends boolean = true> {
  background?: T;
  heading?: T;
  subhead?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              appearance?: T;
              type?: T;
              newTab?: T;
              label?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlockType_select".
 */
export interface FormBlockTypeSelect<T extends boolean = true> {
  formType?: T;
  background?: T;
  heading?: T;
  intro?: T;
  successMessage?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  excerpt?: T;
  heroImage?: T;
  heroImageUrl?: T;
  content?: T;
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        style?: T;
        images?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
              caption?: T;
              id?: T;
            };
        videoUrl?: T;
        videoPoster?: T;
        videoCaption?: T;
        id?: T;
      };
  playlist?: T;
  playlistPart?: T;
  authors?: T;
  publishedAt?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playlists_select".
 */
export interface PlaylistsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  coverImage?: T;
  coverImageUrl?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  category?: T;
  mediaType?: T;
  image?: T;
  videoUrl?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  relationship?: T;
  photo?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  department?: T;
  photo?: T;
  bio?: T;
  isLeadership?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admissions-inquiries_select".
 */
export interface AdmissionsInquiriesSelect<T extends boolean = true> {
  parentName?: T;
  email?: T;
  phone?: T;
  childAge?: T;
  childGrade?: T;
  childAgeOrGrade?: T;
  interest?: T;
  message?: T;
  sourcePage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-bookings_select".
 */
export interface TourBookingsSelect<T extends boolean = true> {
  parentName?: T;
  email?: T;
  phone?: T;
  childAge?: T;
  childGrade?: T;
  childAgeOrGrade?: T;
  preferredDate?: T;
  preferredTime?: T;
  heardAbout?: T;
  notes?: T;
  sourcePage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "summer-camp-registrations_select".
 */
export interface SummerCampRegistrationsSelect<T extends boolean = true> {
  parentName?: T;
  email?: T;
  phone?: T;
  childAge?: T;
  childGrade?: T;
  preferredCampus?: T;
  message?: T;
  sourcePage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admission-applications_select".
 */
export interface AdmissionApplicationsSelect<T extends boolean = true> {
  studentName?: T;
  previousSchool?: T;
  previousCurriculum?: T;
  currentGrade?: T;
  gradeApplyingTo?: T;
  preferredCampus?: T;
  applicationDate?: T;
  childFirstName?: T;
  childMiddleName?: T;
  childLastName?: T;
  gender?: T;
  dateOfBirth?: T;
  placeOfBirth?: T;
  nationality?: T;
  citizenship?: T;
  passportNumber?: T;
  motherTongue?: T;
  secondLanguage?: T;
  primaryContact?: T;
  fatherSalutation?: T;
  fatherFirstName?: T;
  fatherMiddleName?: T;
  fatherLastName?: T;
  fatherNationality?: T;
  fatherOccupation?: T;
  fatherPassport?: T;
  fatherPassportExpiry?: T;
  fatherNationalId?: T;
  fatherMobile?: T;
  fatherBusinessPhone?: T;
  fatherEmergencyPhone?: T;
  fatherEmail?: T;
  fatherWorkEmail?: T;
  motherSalutation?: T;
  motherFirstName?: T;
  motherMiddleName?: T;
  motherLastName?: T;
  motherNationality?: T;
  motherOccupation?: T;
  motherPassport?: T;
  motherPassportExpiry?: T;
  motherNationalId?: T;
  motherMobile?: T;
  motherBusinessPhone?: T;
  motherEmergencyPhone?: T;
  motherEmail?: T;
  motherWorkEmail?: T;
  hasSiblings?: T;
  isStaffChild?: T;
  siblingDetails?: T;
  hasHealthConditions?: T;
  needsTreatment?: T;
  healthDetails?: T;
  hasLearningNeeds?: T;
  hasDisability?: T;
  learningNeedsDetails?: T;
  hasAllergies?: T;
  allergyDetails?: T;
  cat4Verbal?: T;
  cat4Quantitative?: T;
  cat4NonVerbal?: T;
  cat4Spatial?: T;
  mediaConsent?: T;
  parentsSeparated?: T;
  transportInterest?: T;
  heardAbout?: T;
  declarationName?: T;
  declarationAccepted?: T;
  sourcePage?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  schoolName?: string | null;
  phones?:
    | {
        number: string;
        id?: string | null;
      }[]
    | null;
  email?: string | null;
  address?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  /**
   * Shown as brand icons in the footer and in any "Follow Nucleus" section, and emitted as sameAs in the Organization schema. Order here does not matter, the site sorts them.
   */
  socials?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'tiktok' | 'x';
        url: string;
        id?: string | null;
      }[]
    | null;
  footerTagline?: string | null;
  footerText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings".
 */
export interface SeoSetting {
  id: number;
  siteName?: string | null;
  /**
   * Use %s for the page title.
   */
  titleTemplate?: string | null;
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  defaultShareImage?: (number | null) | Media;
  twitterHandle?: string | null;
  organization?: {
    legalName?: string | null;
    foundingYear?: string | null;
    logo?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  schoolName?: T;
  phones?:
    | T
    | {
        number?: T;
        id?: T;
      };
  email?: T;
  address?: T;
  latitude?: T;
  longitude?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footerTagline?: T;
  footerText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings_select".
 */
export interface SeoSettingsSelect<T extends boolean = true> {
  siteName?: T;
  titleTemplate?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultShareImage?: T;
  twitterHandle?: T;
  organization?:
    | T
    | {
        legalName?: T;
        foundingYear?: T;
        logo?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'pages'
      | 'posts'
      | 'playlists'
      | 'media'
      | 'gallery'
      | 'testimonials'
      | 'faq'
      | 'staff'
      | 'admissions-inquiries'
      | 'tour-bookings'
      | 'summer-camp-registrations'
      | 'admission-applications'
      | 'redirects'
      | 'users'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}